---
- name: "Run Playbook Against New Hosts"
  hosts: all
  gather_facts: no
  tasks:
    - name: Wait for Hosts
      wait_for:
        port: 22
        host: '{{ (ansible_ssh_host|default(ansible_host))|default(inventory_hostname) }}'
        search_regex: OpenSSH
        delay: 10
      connection: local
